services:
  server:
    image: judge0/judge0:1.13.1
    env_file: judge0.conf
    volumes:
      - ./judge0.conf:/etc/judge0.conf:ro
    tmpfs:
      - /box
      - /tmp
    ports:
      - "2358:2358"
    privileged: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    depends_on:
      - db
      - redis
    networks:
      - intellijudge_network

  worker:
    image: judge0/judge0:1.13.1
    env_file: judge0.conf
    environment:
      COUNT: 1
    command: ["bash", "-c", "mkdir -p /sys/fs/cgroup/memory && mount -t cgroup -o memory cgroup /sys/fs/cgroup/memory || true && exec ./scripts/workers"]
    volumes:
      - ./judge0.conf:/etc/judge0.conf:ro
    tmpfs:
      - /box
      - /tmp
    privileged: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    depends_on:
      - db
      - redis
    networks:
      - intellijudge_network

  db:
    image: postgres:13.0
    env_file: judge0.conf
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - intellijudge_network

  redis:
    image: redis:6.0
    command: [ "bash", "-c", 'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"' ]
    env_file: judge0.conf
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - intellijudge_network

volumes:
  postgres-data:
  redis-data:

networks:
  intellijudge_network:
    external: true
